server:
  port: 9012

spring:
  application:
    name: actors-service
  profiles:
    active: LOCAL
  config:
    import: configserver:http://configuration-server:8888/
    # 'configuration-server' - is a container name (see more about Docker's networks DNS...)
